<a href="https://colab.research.google.com/github/SinhaUma/Covid19/blob/master/mlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [4]:
import pandas as pd
data = pd.read_csv(r'/content/wine.data', names=['A','B','C','D','E','F','G','H','I','J','K','L','M','N'])

In [5]:
data

A      B     C     D     E    F     G     H     I     J      K     L  \
0    1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04   
1    1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05   
2    1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03   
3    1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86   
4    1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04   
..  ..    ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   
173  3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64   
174  3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70   
175  3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59   
176  3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60   
177  3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61   

        M     N  
0    3.92  1065  
1    3.40  1050  
2    3.17  1185  
3    3.45  1480  
4    2.93   735  
..    ...   ...  
173  1.74   740  
174  1.56   750  
175  1.56   835  
176  1.62   840  
177  1.60   560  

[178 rows x 14 columns]

In [30]:
x = data.iloc[:,1:]
y = data["A"]

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [32]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_trainscaled=scaler.fit_transform(X_train)
X_testscaled=scaler.transform(X_test)

In [33]:
from tensorflow.keras.utils import to_categorical
y_train_ohe = to_categorical(y_train)
y_test_ohe = to_categorical(y_test)

In [34]:
print(X_trainscaled.shape)
print(X_testscaled.shape)
print(y_train_ohe.shape)
print(y_test_ohe.shape)

(142, 13)
(36, 13)
(142, 4)
(36, 4)


In [12]:
y_train_ohe.shape

(142, 4)

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras .layers import Dense,Input,Dropout
from tensorflow.keras.optimizers import Adam

In [36]:
model = Sequential()
model.add(Input(13))
model.add(Dense(units=13,activation="relu"))
model.add(Dense(units=13,activation="relu"))
model.add(Dense(units=13,activation="relu"))
model.add(Dropout(0.1))
model.add(Dense(4,activation="softmax"))

In [37]:
model.compile(optimizer=tf.keras.optimizers.Adam(),
                  loss="categorical_crossentropy",
                  metrics=["accuracy"])

In [39]:
model.fit(x=X_trainscaled, y= y_train_ohe,epochs=100, validation_data=(X_trainscaled, y_train_ohe))

Epoch 1/100
5/5 [==============================] - 0s 22ms/step - loss: 0.0171 - accuracy: 0.9930 - val_loss: 0.0013 - val_accuracy: 1.0000
Epoch 2/100
5/5 [==============================] - 0s 15ms/step - loss: 0.0031 - accuracy: 1.0000 - val_loss: 0.0013 - val_accuracy: 1.0000
Epoch 3/100
5/5 [==============================] - 0s 14ms/step - loss: 0.0046 - accuracy: 1.0000 - val_loss: 0.0013 - val_accuracy: 1.0000
Epoch 4/100
5/5 [==============================] - 0s 14ms/step - loss: 0.0066 - accuracy: 1.0000 - val_loss: 0.0012 - val_accuracy: 1.0000
Epoch 5/100
5/5 [==============================] - 0s 15ms/step - loss: 0.0149 - accuracy: 0.9930 - val_loss: 0.0012 - val_accuracy: 1.0000
Epoch 6/100
5/5 [==============================] - 0s 15ms/step - loss: 0.0022 - accuracy: 1.0000 - val_loss: 0.0011 - val_accuracy: 1.0000
Epoch 7/100
5/5 [==============================] - 0s 15ms/step - loss: 0.0031 - accuracy: 1.0000 - val_loss: 0.0011 - val_accuracy: 1.0000
Epoch 8/100
5/5 [===

In [40]:
preds = model.predict(X_testscaled)

2/2 [==============================] - 0s 5ms/step


In [23]:
from sklearn.metrics import confusion_matrix, classification_report, r2_score

In [43]:
import numpy as np
pred = np.argmax(preds, axis=1)


In [44]:
pred

array([1, 1, 3, 1, 2, 1, 2, 3, 2, 3, 1, 3, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2,
       2, 3, 3, 3, 2, 2, 2, 1, 1, 2, 3, 1, 1, 1])

In [50]:
import numpy as np
rounded_labels=np.argmax(y_test_ohe, axis=1)
rounded_labels[1]

1

In [52]:
rounded_labels

array([1, 1, 3, 1, 2, 1, 2, 3, 2, 3, 1, 3, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2,
       2, 3, 3, 3, 2, 2, 2, 1, 1, 2, 3, 1, 1, 1])

In [53]:
print (confusion_matrix(rounded_labels, pred))

[[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]
